# Generated by Django 2.2.10 on 2021-09-12 05:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210911_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='VIN',
            new_name='VIN_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='number',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_of_last_service',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 0, 27, 13, 229337)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 0, 27, 13, 229337)),
        ),
    ]
