# Generated by Django 2.2.10 on 2021-09-12 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('VIN', models.CharField(default=' ', max_length=50)),
                ('number', models.IntegerField()),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_service', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
